### ISSUE TITLE
关于训练自己的数据问题

### ISSUE THREAD

**Issue by YYYYWD** [xiaochus/TrafficFlowPrediction#2]
请问一下作者。看了一下你给出的test.csv和train.csv的数据样式。我发现这里面的数据日期有些是隔了几天的，请问原数据集就是这样的吗？如果我要把自己的数据导入进去，是要写成test.csv和train.csv的格式再训练对吗？代码里面还要改一些什么呢？

**Comment by xiaochus** [comment]
@YYYYWD 日期间隔是我这边数据本身有些问题，如果要用自己的数据训练，只需要保证csv格式一致即可，参数根据自己的需要进行调整。

**Comment by YYYYWD** [comment]
@xiaochus 好的很感谢你。但是我不太明白train.csv当中的哪一个部分是训练的先前数据，哪一部分是训练的正确结果数据。test.csv中呢？

**Comment by CYBruce** [comment]
@YYYYWD train.csv中训练的特征是当前时刻前一小时每五分钟的流量，正确结果是这个时刻的流量。举个例子，如果现在是要预测10:00的流量，那么就要根据过去一个小时的流量数据（9:00-9:55每五分钟一个值）来预测十点的流量。不知道这样解释清楚吗？
